heat_template_version: 2015-10-15

description: | 
  This template builds the OpenStack cleanvm virtual machines for various cloud
  sources (including a TESTHEAD flag) and images.

parameters:
  TESTHEAD:
    type: string
    default: '1'
    description: >
      Test packages from the staging repository (defaults to `1`, since this
      job normally gates the transition from staging to non-staging.
  automation_branch:
    default: master
    type: string
    description: An alternate branch to use for the automation repository
  automation_repo:
    default: https://github.com/suse-cloud/automation.git
    type: string
    description: The repository URL to clone the automation repository from
  cloudsource:
    type: string
    default: openstackmitaka
    description: The Cloud source to use.
  floating_network:
    type: string
    default: floating
    description: The network to draw floating IPs from.
  image:
    type: string
    default: SLES12-SP1-JeOS-for-OpenStack-Cloud.x86_64-1.1.1-Build24.6
    description: The Glance image to use for the cleanvm machine
  flavor:
    type: string
    default: m1.large
    description: The Nova flavor to use for the cleanvm machine
  key_name:
    type: string
    description: The SSH key to copy into the cleanvm machine's authorized_keys
  quickstart_repo:
    default: ''
    type: string
    description: > 
      The URL of an openstack-quickstart fork to use instead of the
      openstack-quickstart package
  quickstart_branch:
    default: master
    type: string
    description: > 
      A branch to use for the openstack-quickstart fork (only effective if
      quickstart_repo is specified)


resources:

  network:
    type: OS::Neutron::Net
    properties:
      name: mynet


  subnet:
    type: OS::Neutron::Subnet
    properties:
      cidr: 10.0.0.1/24
      name: mysubnet
      network:
        get_resource: network

  cleanvm:
    type: OS::Nova::Server
    properties:
      name: cleanvm
      config_drive: true
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: port }
      user_data_format: RAW
      user_data:
        str_replace:
          params:
            _cloudsource: { get_param: cloudsource }
            _TESTHEAD: { get_param: TESTHEAD }
            _automation_repo: { get_param: automation_repo }
            _automation_branch: { get_param: automation_branch }
            _quickstart_repo: { get_param: quickstart_repo }
            _quickstart_branch: { get_param: quickstart_branch }
          template: |
            #!/bin/sh -x
            exec >> /root/cleanvm.log 2>&1
            export TESTHEAD=_TESTHEAD
            export cloudsource=_cloudsource
            export automation_repo=_automation_repo
            export automation_branch=_automation_branch
            export quickstart_repo=_quickstart_repo
            export quickstart_branch=_quickstart_branch

            . /etc/os-release; # retrieve VERSION_ID

            zypper='zypper --non-interactive'

            case "$VERSION_ID" in
              "12.2")
                $zypper ar 'http://smt-internal.opensuse.org/repo/$RCE/SUSE/Products/SLE-SERVER/12-SP1/x86_64/product/' SLE12-SP1-Pool
                $zypper ar -f 'http://smt-internal.opensuse.org/repo/$RCE/SUSE/Updates/SLE-SERVER/12-SP1/x86_64/update/' SLES12-SP1-Updates
               ;;
              "12.1")
                $zypper ar 'http://smt-internal.opensuse.org/repo/$RCE/SUSE/Products/SLE-SERVER/12-SP1/x86_64/product/' SLE12-SP1-Pool
                $zypper ar -f 'http://smt-internal.opensuse.org/repo/$RCE/SUSE/Updates/SLE-SERVER/12-SP1/x86_64/update/' SLES12-SP1-Updates
               ;;
              "12")
                $zypper ar 'http://smt-internal.opensuse.org/repo/$RCE/SUSE/Products/SLE-SERVER/12/x86_64/product/' SLES12-Pool
                $zypper ar -f 'http://smt-internal.opensuse.org/repo/$RCE/SUSE/Updates/SLE-SERVER/12/x86_64/update/' SLES12-Updates
               ;;
              *)
               ;;
            esac

            # override openstack-quickstart if an alternate repo was specified
            if [ -n "$quickstart_repo" ]; then
              git clone $quickstart_repo  --branch $quickstart_branch /root/openstack-quickstart
              (cd /root/openstack-quickstart; make install)
            fi

            zypper --non-interactive install git-core
            git clone https://github.com/suse-cloud/automation.git --branch $automation_branch /root/automation

            zypper --non-interactive install -f kernel-default-3.12.53-60.30.1
            $zypper remove kernel-default-base-3.12.57-60.35.1
            #sh -x /root/automation/scripts/jenkins/qa_openstack.sh &&
            touch /root/cleanvm_finished

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network:
          get_param: floating_network


  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: router }
      subnet: { get_resource: subnet }


  floatingip:
    type: OS::Neutron::FloatingIP
    properties:
      port_id: { get_resource: port }
      floating_network:
        get_param: floating_network


  allow_inbound:
    type: OS::Neutron::SecurityGroup
    properties:
      description: "Allow inbound SSH and HTTP traffic"
      name: allow inbound SSH and ICMP from anywhere
      rules:
        - direction: ingress
          remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp


  port:
    type: OS::Neutron::Port
    properties:
      network:
        get_resource: network
      security_groups:                # NEW
        - get_resource: allow_inbound # NEW


outputs:
  floating_ip:
    value:
      get_attr:
        - floatingip
        - floating_ip_address

